[package]
name = "test_pinv"
version = "0.1.0"
authors = ["Ramla-I <ijazramla@gmail.com>"]
edition = "2018"

[dependencies.lin_alg]
git = "https://github.com/Ramla-I/lin_alg.git"


[dependencies.num-complex]
version = "0.2"
default-features = false

[dependencies.rand]
version = "0.6.5"
